INSERT IGNORE INTO place (name, city, region, category, teaser) VALUES

('Hồ Gươm', 'Hà Nội', 'Miền Bắc', 'Thiên nhiên', 'Trái tim của thủ đô, nơi Tháp Rùa soi bóng giữa hồ và gắn liền với nhiều câu chuyện lịch sử.'),
('Phố Cổ Hà Nội', 'Hà Nội', 'Miền Bắc', 'Phố cổ & làng nghề', '36 phố phường với những căn nhà cổ, hàng quán truyền thống và không khí đặc trưng của Hà Nội.'),
('Vịnh Hạ Long', 'Quảng Ninh', 'Miền Bắc', 'Thiên nhiên', 'Hàng nghìn đảo đá vôi nhô lên giữa làn nước xanh, tạo nên một trong những cảnh quan nổi tiếng nhất Việt Nam.'),
('Tràng An', 'Ninh Bình', 'Miền Bắc', 'Thiên nhiên', 'Quần thể núi đá vôi, sông nước và hang động tạo nên khung cảnh thiên nhiên ấn tượng.'),
('Fansipan', 'Lào Cai', 'Miền Bắc', 'Thiên nhiên', 'Nóc nhà Đông Dương, nơi du khách có thể chinh phục đỉnh núi và ngắm biển mây từ trên cao.'),
('Chùa Một Cột', 'Hà Nội', 'Miền Bắc', 'Chùa & đền', 'Ngôi chùa có kiến trúc độc đáo được xây dựng trên một cột đá giữa hồ sen.'),
('Văn Miếu - Quốc Tử Giám', 'Hà Nội', 'Miền Bắc', 'Văn hóa - lịch sử', 'Di tích nổi tiếng gắn với truyền thống giáo dục và khoa bảng của Việt Nam.'),
('Bảo tàng Dân tộc học Việt Nam', 'Hà Nội', 'Miền Bắc', 'Bảo tàng', 'Nơi giới thiệu đời sống, văn hóa và phong tục của 54 dân tộc Việt Nam.'),
('Thác Bản Giốc', 'Cao Bằng', 'Miền Bắc', 'Thiên nhiên', 'Thác nước hùng vĩ giữa núi rừng Cao Bằng với nhiều tầng nước đổ xuống tạo nên cảnh quan ấn tượng.'),
('Chợ Đồng Xuân', 'Hà Nội', 'Miền Bắc', 'Chợ & mua sắm', 'Một trong những khu chợ lâu đời và nổi tiếng nhất Hà Nội, tập trung nhiều mặt hàng và đặc sản.'),

('Đại Nội Huế', 'Thừa Thiên Huế', 'Miền Trung', 'Văn hóa - lịch sử', 'Quần thể cung điện cổ kính nằm trong Kinh thành Huế, gắn liền với triều Nguyễn.'),
('Chùa Thiên Mụ', 'Thừa Thiên Huế', 'Miền Trung', 'Chùa & đền', 'Ngôi chùa cổ nằm bên dòng sông Hương, nổi bật với tháp Phước Duyên bảy tầng.'),
('Phố cổ Hội An', 'Quảng Nam', 'Miền Trung', 'Phố cổ & làng nghề', 'Những dãy nhà cổ, đèn lồng và con phố nhỏ tạo nên vẻ đẹp đặc trưng của Hội An.'),
('Cầu Vàng', 'Đà Nẵng', 'Miền Trung', 'Vui chơi & giải trí', 'Cây cầu nổi tiếng nằm giữa núi rừng Bà Nà Hills với thiết kế đôi bàn tay khổng lồ nâng đỡ.'),
('Biển Mỹ Khê', 'Đà Nẵng', 'Miền Trung', 'Biển & đảo', 'Bãi biển nổi tiếng với bờ cát dài, nước biển trong và nhiều hoạt động vui chơi ven biển.'),
('Hồ Xuân Hương', 'Lâm Đồng', 'Miền Trung', 'Thiên nhiên', 'Mặt hồ thơ mộng nằm giữa trung tâm Đà Lạt, thích hợp đi dạo, đạp xe và ngắm cảnh.'),
('Bảo tàng Điêu khắc Chăm', 'Đà Nẵng', 'Miền Trung', 'Bảo tàng', 'Nơi lưu giữ nhiều hiện vật và tác phẩm điêu khắc đặc sắc của nền văn hóa Chăm Pa.'),
('Thác Datanla', 'Lâm Đồng', 'Miền Trung', 'Thiên nhiên', 'Thác nước giữa rừng thông với nhiều hoạt động trải nghiệm và vui chơi ngoài trời.'),
('Đảo Lý Sơn', 'Quảng Ngãi', 'Miền Trung', 'Biển & đảo', 'Hòn đảo núi lửa với cảnh quan biển, vách đá và những cánh đồng tỏi đặc trưng.'),
('Bà Nà Hills', 'Đà Nẵng', 'Miền Trung', 'Vui chơi & giải trí', 'Khu du lịch trên núi kết hợp cảnh quan, vui chơi giải trí và nhiều công trình kiến trúc độc đáo.'),
('Đồi cát Mũi Né', 'Bình Thuận', 'Miền Trung', 'Thiên nhiên', 'Những đồi cát vàng và đỏ trải dài, tạo nên khung cảnh đặc biệt và thích hợp cho các hoạt động trải nghiệm.'),

('Chợ Bến Thành', 'TP. Hồ Chí Minh', 'Miền Nam', 'Chợ & mua sắm', 'Biểu tượng của Sài Gòn với nhiều gian hàng bán đặc sản, đồ lưu niệm và các món ăn địa phương.'),
('Địa đạo Củ Chi', 'TP. Hồ Chí Minh', 'Miền Nam', 'Văn hóa - lịch sử', 'Hệ thống đường hầm dưới lòng đất gắn liền với lịch sử kháng chiến của Việt Nam.'),
('Chợ nổi Cái Răng', 'Cần Thơ', 'Miền Nam', 'Chợ & mua sắm', 'Khu chợ nổi đặc trưng của miền Tây với những chiếc ghe buôn bán trái cây và đặc sản trên sông.'),
('Bãi Sao', 'Kiên Giang', 'Miền Nam', 'Biển & đảo', 'Bãi biển nổi tiếng tại Phú Quốc với cát trắng, nước biển trong xanh và cảnh quan yên bình.'),
('Núi Bà Đen', 'Tây Ninh', 'Miền Nam', 'Chùa & đền', 'Ngọn núi cao nhất Nam Bộ với quần thể tâm linh và hệ thống cáp treo trên núi.'),
('Bảo tàng Chứng tích Chiến tranh', 'TP. Hồ Chí Minh', 'Miền Nam', 'Bảo tàng', 'Nơi trưng bày nhiều hiện vật, hình ảnh và tư liệu về chiến tranh tại Việt Nam.'),
('Côn Đảo', 'Bà Rịa - Vũng Tàu', 'Miền Nam', 'Biển & đảo', 'Quần đảo có biển xanh, rừng tự nhiên và nhiều địa điểm mang giá trị lịch sử.'),
('Suối Tiên', 'TP. Hồ Chí Minh', 'Miền Nam', 'Vui chơi & giải trí', 'Khu vui chơi kết hợp các công trình mô phỏng văn hóa và truyền thuyết Việt Nam.'),
('Làng nổi Tân Lập', 'Long An', 'Miền Nam', 'Thiên nhiên', 'Khu du lịch sinh thái giữa rừng tràm, thích hợp đi thuyền và khám phá thiên nhiên miền Tây.');